set(CMAKE_AR                        gcc-ar${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_ASM_COMPILER              gcc${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_C_COMPILER                gcc${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_CXX_COMPILER              g++${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_LINKER                    ld${CMAKE_EXECUTABLE_SUFFIX})
set(CMAKE_OBJCOPY                   objcopy${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_RANLIB                    ranlib${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_SIZE                      size${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_STRIP                     strip${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_GCOV                      gcov${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

if (cmake_build_type_tolower STREQUAL "debug" OR cmake_build_type_tolower STREQUAL "coverage" OR cmake_build_type_tolower STREQUAL "relwithdebinfo")
	message(STATUS "+++ Setting debug flags +++")
	add_compile_options(-ggdb)
endif()
